# Generated by Django 4.2.21 on 2025-05-20 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
