# Generated by Django 4.2.21 on 2025-05-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0004_remove_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='pic',
            field=models.ImageField(null=True, upload_to='pet_shop/static/images/'),
        ),
    ]
