# Generated by Django 4.2.21 on 2025-05-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0005_alter_contact_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.ImageField(null=True, upload_to='pet_shop/images/'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='pic',
            field=models.ImageField(null=True, upload_to='pet_shop/images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='pic',
            field=models.ImageField(null=True, upload_to='pet_shop/images/'),
        ),
    ]
