# Generated by Django 4.2.21 on 2025-05-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0008_shoppingcart_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='balanse',
            field=models.IntegerField(default=0),
        ),
    ]
