# Generated by Django 4.2.21 on 2025-05-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0009_serviceuser_balanse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceuser',
            old_name='balanse',
            new_name='balance',
        ),
    ]
