# Generated by Django 4.2.21 on 2025-05-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0011_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceuser',
            name='pic',
            field=models.ImageField(null=True, upload_to='pet_shop/images/'),
        ),
    ]
