# Generated by Django 4.2.25 on 2025-10-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0013_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='text',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='certificate',
            field=models.TextField(blank=True, null=True, verbose_name='Сертификат'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='description',
            field=models.TextField(default='Информация о компании пока не добавлена', verbose_name='Информация о компании'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='history',
            field=models.TextField(blank=True, null=True, verbose_name='История по годам'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Логотип'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(default='Название не указано', max_length=255, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(blank=True, null=True, verbose_name='Реквизиты'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Видео (YouTube или другое)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='pet_shop/images/', verbose_name='Логотип'),
        ),
    ]
