# Generated by Django 4.2.25 on 2025-10-15 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0014_remove_companyinfo_text_companyinfo_certificate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео компании'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о компании'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название компании'),
        ),
    ]
