# Generated by Django 4.2.25 on 2025-10-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0015_remove_companyinfo_video_url_companyinfo_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='pet_shop/images/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='pet_shop/videos/', verbose_name='Видео компании'),
        ),
    ]
