# Generated by Django 4.2.25 on 2025-10-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0016_alter_companyinfo_logo_alter_companyinfo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pic',
            field=models.ImageField(null=True, upload_to='pet_shop/images/news/'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='pet_shop/images/partners/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic',
            field=models.ImageField(null=True, upload_to='pet_shop/images/products/'),
        ),
        migrations.AlterField(
            model_name='serviceuser',
            name='pic',
            field=models.ImageField(null=True, upload_to='pet_shop/images/avatar/'),
        ),
    ]
