# Generated by Django 4.2.25 on 2025-12-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0017_alter_news_pic_alter_partner_logo_alter_product_pic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet_shop/images/banner/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SliderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop', models.BooleanField(default=True, verbose_name='Зацикливание (loop)')),
                ('navs', models.BooleanField(default=True, verbose_name='Стрелки навигации (navs)')),
                ('pags', models.BooleanField(default=True, verbose_name='Пагинация (pags)')),
                ('auto', models.BooleanField(default=True, verbose_name='Автопереключение (auto)')),
                ('stop_mouse_hover', models.BooleanField(default=True, verbose_name='Остановка при наведении (stopMouseHover)')),
                ('delay', models.IntegerField(default=5, verbose_name='Задержка в секундах (delay)')),
            ],
            options={
                'verbose_name': 'Настройки слайдера',
                'verbose_name_plural': 'Настройки слайдера',
            },
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='pet_shop/images/logo/', verbose_name='Логотип'),
        ),
    ]
