# Generated by Django 4.2.25 on 2025-12-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0018_slide_slidersettings_alter_companyinfo_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slidersettings',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='slidersettings',
            name='loop',
        ),
        migrations.RemoveField(
            model_name='slidersettings',
            name='navs',
        ),
        migrations.RemoveField(
            model_name='slidersettings',
            name='pags',
        ),
        migrations.RemoveField(
            model_name='slidersettings',
            name='stop_mouse_hover',
        ),
    ]
