# Generated by Django 4.2.25 on 2025-12-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0019_remove_slidersettings_auto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidersettings',
            name='auto',
            field=models.BooleanField(default=True, verbose_name='Автопереключение (auto)'),
        ),
        migrations.AddField(
            model_name='slidersettings',
            name='loop',
            field=models.BooleanField(default=True, verbose_name='Зацикливание (loop)'),
        ),
        migrations.AddField(
            model_name='slidersettings',
            name='navs',
            field=models.BooleanField(default=True, verbose_name='Стрелки навигации (navs)'),
        ),
        migrations.AddField(
            model_name='slidersettings',
            name='pags',
            field=models.BooleanField(default=True, verbose_name='Пагинация (pags)'),
        ),
        migrations.AddField(
            model_name='slidersettings',
            name='stop_mouse_hover',
            field=models.BooleanField(default=True, verbose_name='Остановка при наведении (stopMouseHover)'),
        ),
    ]
