# Generated by Django 4.2.25 on 2025-12-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0020_slidersettings_auto_slidersettings_loop_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['full_name'], 'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='slide',
            options={'ordering': ['order'], 'verbose_name': 'Slide', 'verbose_name_plural': 'Slides'},
        ),
        migrations.AlterModelOptions(
            name='slidersettings',
            options={'verbose_name': 'Slider Settings', 'verbose_name_plural': 'Slider Settings'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.TextField(default='', verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='Full Name'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=50, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='contact',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pet_shop/images/contacts/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(upload_to='pet_shop/images/partners/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(upload_to='pet_shop/images/banner/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Display Order'),
        ),
        migrations.AlterField(
            model_name='slidersettings',
            name='auto',
            field=models.BooleanField(default=True, verbose_name='Auto Play (auto)'),
        ),
        migrations.AlterField(
            model_name='slidersettings',
            name='delay',
            field=models.IntegerField(default=5, verbose_name='Delay (seconds)'),
        ),
        migrations.AlterField(
            model_name='slidersettings',
            name='loop',
            field=models.BooleanField(default=True, verbose_name='Loop'),
        ),
        migrations.AlterField(
            model_name='slidersettings',
            name='navs',
            field=models.BooleanField(default=True, verbose_name='Navigation Arrows (navs)'),
        ),
        migrations.AlterField(
            model_name='slidersettings',
            name='pags',
            field=models.BooleanField(default=True, verbose_name='Pagination (pags)'),
        ),
        migrations.AlterField(
            model_name='slidersettings',
            name='stop_mouse_hover',
            field=models.BooleanField(default=True, verbose_name='Stop on Mouse Hover (stopMouseHover)'),
        ),
    ]
